server:
  port: 8080
  servlet:
    context-path: /customFrameWork

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/captruepackage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
          cache:
            use_query_cache: false
            use_second_level_cache: false
            region:
              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          dialect: org.hibernate.dialect.MySQL5Dialect
          show_sql: true
      generate-ddl: false
  mail:
    host: smtp.qq.com
    username:
    password:
    port: 587
    default-encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 300
        ## 连接池中的最大空闲连接
        max-idle: 100
        ## 连接池中的最小空闲连接
        min-idle: 100
      ## 连接超时时间（毫秒）
      timeout: 1000

#mybatis:
#  typeAliasesPackage: com.example.demo.entity
#  mapperLocations: classpath:mapper/*.xml
#mybatis-plus:
#  global-config:
#    db-config:
#      #Sequence序列接口实现类配置
#      key-generator: com.baomidou.mybatisplus.extension.incrementer.OracleKeyGenerator
